services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: moviedb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    #   - ./postgresql.conf:/etc/postgresql/postgresql.conf  # Menambahkan file konfigurasi
    # command: -c 'config_file=/etc/postgresql/postgresql.conf'  # Menggunakan file konfigurasi khusus

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"
    depends_on:
      - db

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/usr/src/app
    depends_on:
      - db

volumes:
  postgres_data:
