services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: moviedb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"
    restart: always
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  server:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ADMIN_EMAIL: admin@email.com
      SERVER_PORT: 3000
      DB_USER: user
      DB_HOST: db
      DB_NAME: moviedb
      DB_PASS: pass
      DB_PORT: 5432
      JWT_SECRET: your-secret-key
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  postgres_data:
  pgadmin_data: