services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: moviedb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 0tiTvjvTL2SLyyUZcRdphrgwxM32Ch5M
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: DLtRFd61i4i15yOlJOJwT9SZcSi6ERMX
    ports:
      - "8081:80"
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  server:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ADMIN_EMAIL: admin@email.com
      SERVER_PORT: 3000
      DB_USER: user
      DB_HOST: db
      DB_NAME: moviedb
      DB_PASS: 0tiTvjvTL2SLyyUZcRdphrgwxM32Ch5M
      DB_PORT: 5432
      JWT_SECRET: n6T53xLzyR4v9sX16bMT8tSSMbKxpmrf
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      - db
  
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"  # Port Redis untuk komunikasi
    volumes:
      - redis_data:/data  # Penyimpanan data Redis (opsional)

volumes:
  postgres_data:
  pgadmin_data: