services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: moviedb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: o61KKz:NP3CJG6$p4.84ke}x1%L4]8Cj
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: kE5H:S9Y;J3Qntx#y%D/G9T]l"(nMr,q
    ports:
      - "8081:80"
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  server:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ADMIN_EMAIL: admin@email.com
      SERVER_PORT: 3000
      DB_USER: user
      DB_HOST: db
      DB_NAME: moviedb
      DB_PASS: o61KKz:NP3CJG6$p4.84ke}x1%L4]8Cj
      DB_PORT: 5432
      JWT_SECRET: Q%._4U4Ym!lR@mi;Gy0XnxKn>xlr0&lR
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  postgres_data:
  pgadmin_data: